begin;

-- Seed shop
insert into public.shop (
  id, spid, department_no, accounting_category, store_name, store_name_furigana,
  store_name_short, phone_number, url, mail, is_web, web_management_id,
  web_management_pw, web_management_url, hostess_page_url, hostess_list_url,
  hostess_attendance_management_url, hostess_management_url, send_hsprofile,
  send_hsattend, send_hsjob, send_ctpoint, send_hsstart, send_hsranking,
  course_fee_style, nomination_fee_style, gm_category, nomination_fee,
  extension_fee, extension_per_minutes, standard_transportation_expenses,
  cancel_fee, is_membership_card, customer_point_initial_former,
  customer_point_initial_latter, is_nomination_plusback,
  membership_number_management, change_fee, card_commission,
  standard_hostess_recieve_rate, extension_style, extension_hostess_recieve_rate,
  panel_nomination_fee, star_price, group_no, business_style, former_start,
  former_end, latter_start, latter_end, is_hs_send_room_no, is_hs_send_end
) values
  (
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    1001,
    1,
    'A',
    'サンプル店舗1',
    'サンプルテンポイチ',
    'サンプル1',
    '0312345678',
    'https://example.com/shop1',
    'shop1@example.com',
    true,
    'web_admin_1',
    'encrypted_password_1',
    'https://web.example.com/shop1',
    'https://web.example.com/shop1/hostess',
    'https://web.example.com/shop1/hostess/list',
    'https://web.example.com/shop1/hostess/attendance',
    'https://web.example.com/shop1/hostess/management',
    'send_hsprofile_1',
    'send_hsattend_1',
    'send_hsjob_1',
    'send_ctpoint_1',
    'send_hsstart_1',
    'send_hsranking_1',
    false,
    false,
    true,
    5000,
    3000,
    10,
    2000,
    1000,
    true,
    100,
    150,
    true,
    false,
    2000,
    500,
    50.00,
    'fixed_rate',
    60.00,
    3000,
    1000,
    1,
    'delivery_health',
    '18:00',
    '22:00',
    '22:00',
    '02:00',
    true,
    false
  ),
  (
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    1002,
    2,
    'B',
    'サンプル店舗2',
    'サンプルテンポニ',
    'サンプル2',
    '0361234567',
    'https://example.com/shop2',
    'shop2@example.com',
    true,
    'web_admin_2',
    'encrypted_password_2',
    'https://web.example.com/shop2',
    'https://web.example.com/shop2/hostess',
    'https://web.example.com/shop2/hostess/list',
    'https://web.example.com/shop2/hostess/attendance',
    'https://web.example.com/shop2/hostess/management',
    'send_hsprofile_2',
    'send_hsattend_2',
    'send_hsjob_2',
    'send_ctpoint_2',
    'send_hsstart_2',
    'send_hsranking_2',
    true,
    true,
    false,
    6000,
    3500,
    15,
    2500,
    1500,
    true,
    120,
    180,
    false,
    true,
    2500,
    600,
    55.00,
    'hostess_specific',
    65.00,
    3500,
    1200,
    2,
    'hotel_health',
    '19:00',
    '23:00',
    '23:00',
    '03:00',
    false,
    true
  ),
  (
    'cccccccc-cccc-cccc-cccc-cccccccccccc',
    1003,
    1,
    'A',
    'サンプル店舗3',
    'サンプルテンポサン',
    'サンプル3',
    '0398765432',
    'https://example.com/shop3',
    'shop3@example.com',
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    false,
    false,
    true,
    4500,
    2800,
    12,
    1800,
    800,
    false,
    80,
    120,
    true,
    false,
    1800,
    450,
    48.00,
    'fixed_rate',
    58.00,
    2800,
    900,
    1,
    'delivery_health',
    '17:00',
    '21:00',
    '21:00',
    '01:00',
    true,
    true
  )
on conflict (id) do nothing;

commit;

