package shop

type ShopDTO struct {
	ID                              string  `json:"id"`
	SPID                            *int    `json:"spid"`
	DepartmentNo                    *int    `json:"department_no"`
	AccountingCategory              *string `json:"accounting_category"`
	StoreName                       *string `json:"store_name"`
	StoreNameFurigana              *string `json:"store_name_furigana"`
	StoreNameShort                  *string `json:"store_name_short"`
	PhoneNumber                     *string `json:"phone_number"`
	URL                             *string `json:"url"`
	Mail                            *string `json:"mail"`
	IsWeb                           *bool   `json:"is_web"`
	WebManagementID                 *string `json:"web_management_id"`
	WebManagementPW                 *string `json:"web_management_pw"`
	WebManagementURL                *string `json:"web_management_url"`
	HostessPageURL                 *string `json:"hostess_page_url"`
	HostessListURL                 *string `json:"hostess_list_url"`
	HostessAttendanceManagementURL *string `json:"hostess_attendance_management_url"`
	HostessManagementURL            *string `json:"hostess_management_url"`
	SendHsprofile                  *string `json:"send_hsprofile"`
	SendHsattend                   *string `json:"send_hsattend"`
	SendHsjob                      *string `json:"send_hsjob"`
	SendCtpoint                    *string `json:"send_ctpoint"`
	SendHsstart                    *string `json:"send_hsstart"`
	SendHsranking                  *string `json:"send_hsranking"`
	CourseFeeStyle                 *bool   `json:"course_fee_style"`
	NominationFeeStyle             *bool   `json:"nomination_fee_style"`
	GmCategory                     *bool   `json:"gm_category"`
	NominationFee                  *int    `json:"nomination_fee"`
	ExtensionFee                   *int    `json:"extension_fee"`
	ExtensionPerMinutes            *int    `json:"extension_per_minutes"`
	StandardTransportationExpenses *int    `json:"standard_transportation_expenses"`
	CancelFee                      *int    `json:"cancel_fee"`
	IsMembershipCard               *bool   `json:"is_membership_card"`
	CustomerPointInitialFormer     *int    `json:"customer_point_initial_former"`
	CustomerPointInitialLatter     *int    `json:"customer_point_initial_latter"`
	IsNominationPlusback          *bool   `json:"is_nomination_plusback"`
	MembershipNumberManagement     *bool   `json:"membership_number_management"`
	ChangeFee                      *int    `json:"change_fee"`
	CardCommission                 *int    `json:"card_commission"`
	StandardHostessRecieveRate     *float64 `json:"standard_hostess_recieve_rate"`
	ExtensionStyle                 *string  `json:"extension_style"`
	ExtensionHostessRecieveRate   *float64 `json:"extension_hostess_recieve_rate"`
	PanelNominationFee             *int     `json:"panel_nomination_fee"`
	StarPrice                      *int     `json:"star_price"`
	GroupNo                        *int     `json:"group_no"`
	BusinessStyle                  *string  `json:"business_style"`
	FormerStart                    *string  `json:"former_start"`
	FormerEnd                      *string  `json:"former_end"`
	LatterStart                    *string  `json:"latter_start"`
	LatterEnd                      *string  `json:"latter_end"`
	IsHsSendRoomNo                 *bool   `json:"is_hs_send_room_no"`
	IsHsSendEnd                    *bool   `json:"is_hs_send_end"`
	CreatedAt                      *string `json:"created_at"`
	UpdatedAt                      *string `json:"updated_at"`
}

